export const BLE_DEVICE_ADDED = 'WEB_BLUETOOTH_STORE_DEVICE_ADDED'
export const BLE_DEVICE_UPDATED = 'WEB_BLUETOOTH_STORE_DEVICE_UPDATED'
export const BLE_DEVICE_REMOVED = 'WEB_BLUETOOTH_STORE_DEVICE_UPDATE'
//
export const BLE_SERVICES_DISCOVERED = 'WEB_BLUETOOTH_STORE_SERVICE_DISCOVERED'
export const BLE_SERVICE_CHANGED = 'WEB_BLUETOOTH_STORE_SERVICE_CHANGED'
//
export const BLE_CHARACTERISTICS_DISCOVERED = 'WEB_BLUETOOTH_STORE_CHARACTERISTICS_DISCOVERED'
export const BLE_CHARACTERISTIC_CHANGED = 'WEB_BLUETOOTH_STORE_CHARACTERISTIC_CHANGED'
