export const BLE_DEVICE_ADDED = 'WEB_BLUETOOTH_STORE_DEVICE_ADDED'
export const BLE_DEVICE_CONNECTED = 'WEB_BLUETOOTH_STORE_DEVICE_CONNECTED'
export const BLE_DEVICE_DISCONNECTED = 'WEB_BLUETOOTH_STORE_DEVICE_DISCONNECTED'
export const BLE_DEVICE_REMOVED = 'WEB_BLUETOOTH_STORE_DEVICE_UPDATE'
//
export const BLE_SERVICE_DISCOVERED = 'WEB_BLUETOOTH_STORE_SERVICE_DISCOVERED'
// export const BLE_SERVICE_CHANGED = 'WEB_BLUETOOTH_STORE_SERVICE_UPDATED'
//
export const BLE_CHARACTERISTIC_DISCOVERED = 'WEB_BLUETOOTH_STORE_CHARACTERISTIC_DISCOVERED'
export const BLE_CHARACTERISTIC_VALUE_CHANGED = 'WEB_BLUETOOTH_STORE_CHARACTERISTIC_VALUE_CHANGED'
