export const BLE_DEVICE_ADDED = 'WEB_BLUETOOTH_STORE_DEVICE_ADDED'
export const BLE_DEVICE_UPDATED = 'WEB_BLUETOOTH_STORE_DEVICE_UPDATED'
export const BLE_DEVICE_REMOVED = 'WEB_BLUETOOTH_STORE_DEVICE_REMOVED'
export const BLE_DEVICE_DISCONNECTED = "WEB_BLUETOOTH_STORE_DEVICE_DISCONNECTED"
export const BLE_DEVICE_ADVERTISMENT_UPDATED = 'WEB_BLUETOOTH_STORE_DEVICE_REMOVED'

//
export const BLE_SERVICE_ADDED =   'WEB_BLUETOOTH_STORE_SERVICE_ADDED'
export const BLE_SERVICE_UPDATED = 'WEB_BLUETOOTH_STORE_SERVICE_UPDATED'
export const BLE_SERVICE_REMOVED = 'WEB_BLUETOOTH_STORE_SERVICE_REMOVED'
//
export const BLE_CHARACTERISTICS_DISCOVERED = 'WEB_BLUETOOTH_STORE_CHARACTERISTICS_DISCOVERED'
export const BLE_CHARACTERISTIC_CHANGED = 'WEB_BLUETOOTH_STORE_CHARACTERISTIC_CHANGED'
